apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: default
spec:
  releaseName: podinfo-dev
  chart:
    #repository: https://charts.rissc.net
    #name: podinfo
    #version: 0.2.1
    repository: https://charts.rissc.net
    path: charts/podinfo
    ref: master
  values:
    image: saschariedel/podinfo:1.0.2
    replicaCount: 1
    hpa:
      enabled: false
